service: revue-server
frameworkVersion: '3'

plugins:
  - serverless-offline

custom:
  # secrets: ${file(secrets.json)}
  serverless-offline:
    ignoreJWTSignature: true

  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Length
    - Authorization
    - user_email

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  stage: dev
  memorySize: 128
  timeout: 5
  environment:
    # JWT_SECRET: ${self:custom.process.env.JWT_SECRET}
    JWT_SECRET: ${ssm:/revue-jwt-secret}
    S3_SECRET: ${ssm:/revue-s3-secret}
    USERS_TABLE: ${self:service}-v5

  httpApi:
    authorizers:
      verifyToken:
        type: request
        functionName: verifyToken
        resultTtlInSeconds: 300
        identitySource: $request.header.Authorization

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: userEmail
            AttributeType: S
          - AttributeName: userName
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
          - AttributeName: userType
            AttributeType: N
        KeySchema:
          - AttributeName: userEmail
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
        GlobalSecondaryIndexes:
          - IndexName: userId-index
            KeySchema:
              - AttributeName: userId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 3
              WriteCapacityUnits: 3

functions:
  hello:
    handler: api/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  verifyToken:
    handler: utils/authorize.authorize

  me:
    handler: api/me.me
    events:
      - httpApi:
          path: /me
          method: get
          authorizer:
            name: verifyToken
            type: request

  presignedUrl:
    handler: api/presignedUrl.presignedUrl
    events:
      - httpApi:
          path: /me/presignedUrl
          method: post
          authorizer:
            name: verifyToken
            type: request

  updateUser:
    handler: api/updateUser.updateUser
    events:
      - httpApi:
          path: /me/updateUser
          method: put
          authorizer:
            name: verifyToken
            type: request

  login:
    handler: api/login.login
    events:
      - httpApi:
          path: /login
          method: post

  registerUser:
    handler: api/registerUser.registerUser
    events:
      - httpApi:
          path: /registerUser
          method: post

  getUser:
    handler: api/getUser.getUser
    events:
      - httpApi:
          path: /getUser/{userId}
          method: get

  getUsers:
    handler: api/getUsers.getUsers
    events:
      - httpApi:
          path: /getUsers
          method: get

  deleteUser:
    handler: api/deleteUser.deleteUser
    events:
      - httpApi:
          path: /deleteUser/{userId}
          method: delete

  # getUserByEmail:
  #   handler: api/getUserByEmail.getUserByEmail
  #   events:
  #     - httpApi:
  #         path: /getUserByEmail
  #         method: get
